Create ns_speex_tilde
TheTelephone/TheTelephone pull request #3
Opened 2016-10-21 12:04 UTC by michalsoloducha

I have tested it for different input parameters and it seems to work fine. Feel free to add modifications/comments.

2016-10-26 11:03 UTC, dennisguse commented on src/signal-processing/ns_speex_tilde
> +#include "ringbuffer.h"
Should not be required.
I will cleanup this include everywhere else.

2016-10-26 11:10 UTC, dennisguse commented
Thanks Michal!
Its a good job!

I just added some comments, and when resolved I will merge it.
And could you add a help file?
I just saw that vad_speex~ also misses the help file and it would be awesome if you could also add one for this external.

2016-10-26 11:13 UTC, dennisguse requested changes
Looks good - just requires some smaller changes.

2016-10-26 11:13 UTC, dennisguse commented on src/signal-processing/ns_speex_tilde
> +
Remove empty line

2016-10-26 11:13 UTC, dennisguse commented on src/signal-processing/ns_speex_tilde
> +  // enable noise suppression
Remove comment

2016-10-26 11:13 UTC, dennisguse commented on src/signal-processing/ns_speex_tilde
> +  // enable noise suppression
And also additional comments, e.g. constructor, destructure etc.

2016-10-26 11:13 UTC, dennisguse commented on src/signal-processing/ns_speex_tilde
> +  ns_speex_tilde_class = class_new (
Please apply the gnu intend tool as described in the README.md

2016-10-26 11:13 UTC, dennisguse commented on src/signal-processing/ns_speex_tilde
> +	A_DEFFLOAT, A_DEFFLOAT, A_DEFFLOAT, 0 // init. values for: frame size, sample rate, max. noise attenuation
Remove comment

2016-10-26 11:13 UTC, dennisguse commented on src/signal-processing/ns_speex_tilde
> +@file ns_speex_tilde.c
Can you rename it to denoise_speex_tilde.c
This allows to understand easier what it actually does/

2016-10-26 11:13 UTC, dennisguse commented on src/signal-processing/ns_speex_tilde
> +  MAX_NOISE_ATT - maximum noise attenuation (negative number) [dB]
@MAX_NOISE_ATT

I would prefer the long version (MAX_NOISE_ATTENUATION) and also the expected range -100..0?
What is the default value?

2016-10-26 11:13 UTC, dennisguse commented on src/signal-processing/ns_speex_tilde
> +  t_int max_noise_att;
long version

2016-10-27 15:44 UTC, michalsoloducha commented on src/signal-processing/ns_speex_tilde
> +  ns_speex_tilde_class = class_new (
I can't find that information in the main readme file.

2016-10-27 15:46 UTC, dennisguse commented on src/signal-processing/ns_speex_tilde
> +  ns_speex_tilde_class = class_new (
Ohh my fault - it is in the DEVELOPER.md

```
indent \
--braces-after-if-line \
--braces-after-func-def-line \
--braces-on-if-line \
--braces-on-func-def-line \
--braces-on-struct-decl-line \
--break-after-boolean-operator \
--break-before-boolean-operator \
--dont-break-function-decl-args \
--dont-break-function-decl-args-end \
--dont-break-procedure-type \
--dont-star-comments \
--space-after-cast \
--no-tabs \
--cuddle-else \
-l999 \
*.{c,h}
```

2016-10-28 18:53 UTC, michalsoloducha commented
Allright, all the requested changes are done. At some point later I will provide the help files for denoise and vad.

2016-10-29 16:56 UTC, dennisguse commented
Code looks good.
I would like to wait until the help file is also ready.
Then it is just one commit ;)

2016-11-08 20:38 UTC, michalsoloducha commented
I have uploaded the help files for denoise_speex and vad_speex. Plus some minor changes.

2016-11-08 22:55 UTC, dennisguse approved these changes

2016-11-08 22:58 UTC, dennisguse commented
One final thing: is t_outlet actually used by denoise_speex_tilde.c?
The required outlet should be made available by generic_codec.h, or?

Could you test if t_outlet is required, and if not remove it?

2016-11-14 14:00 UTC, michalsoloducha commented
Ok, so I got rid of unnecessary audio outlet declaration made some minor fixes.

2016-11-14 15:56 UTC, merged